spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 66ccff
    url: jdbc:mysql://localhost/test?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell