spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 66ccff
    url: jdbc:mysql://127.0.0.1:3306/blog1_0
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /blog
  port: 8081

project-url:
  blog: